# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90a3e0251f546764bd3cdb2ecf9a45a4b0ab3a37da60f312bf68a1d28bea34d2abeb12ca2ced657367503b9cc67de376bd09e5bb70511b9329b3ee2f3897291e

test:
  secret_key_base: e21342ff424f2f14ae47b6d921d2abaa888549579640eb9798f89ef5e9d6291689f46db6df17572dfa4f95c0de8ef7b1f1aa7bd4f1e767c5eacd5701c6074565

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
